# TODO:
# - Add Golint
# - Add coverage tool

sudo: required

env:
  - DEP_VERSION="0.4.1"

language: go
go:
  - "1.10.3"

services:
  - docker

branches:
  only:
  - master
  - dev
  - qa

before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; 
    then export TAG=latest;
    else export TAG=$TRAVIS_BRANCH; fi
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - docker swarm init
  - docker network create --driver=overlay --attachable pcp
  - travis_wait 10 docker pull ramrodpcp/interpreter-plugin:$TAG

install:  
  - dep ensure
  - go vet
  - go build -race
  - go test -v -parallel 1 github.com/ramrod-project/backend-controller-go/dockerservicemanager
  - go test -v -parallel 1 github.com/ramrod-project/backend-controller-go/rethink
  - go test -v -parallel 1 github.com/ramrod-project/backend-controller-go/errorhandler
  - make

before_script:
  - travis_wait 10 docker pull ramrodpcp/database-brain:$TAG

script:
  - docker build -t ramrodpcp/backend-contoller:$TAG .
  - docker run -d --name rethinkdb --network pcp -p 28015:28015 ramrodpcp/database-brain:$TAG
  - docker run -d --name controller --network pcp -v /var/run/docker.sock:/var/run/docker.sock ramrodpcp/backend-contoller:$TAG
  - sleep 15
  - docker service ls
  - docker logs controller
  - docker stop controller
  - docker stop rethinkdb

notifications:
  slack: ramrod-project:GDF82rRYDg3KSekrT3GA24qO